databases:
  - name: tailwind
    plan: free
    databaseName: tailwind
    user: rafael

services:
  - type: web
    plan: free
    name: tailwind
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn tailwind.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tailwind
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4