# Generated by Django 5.1.3 on 2024-12-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('SurveyQuestionId', models.IntegerField()),
                ('AnswerId', models.IntegerField()),
            ],
        ),
    ]
