# Generated by Django 5.1.3 on 2024-12-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_surveyanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
    ]
