# Generated by Django 5.1.3 on 2024-12-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_surveyanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SurveyQuestionId', models.IntegerField()),
                ('AnswerId', models.IntegerField()),
            ],
        ),
    ]
