# Generated by Django 5.1.3 on 2024-12-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_surveyquestion_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyAnswer',
            new_name='QuestionAnswer',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='SurveyQuestionId',
            new_name='QuestionId',
        ),
    ]
