# Generated by Django 5.1.3 on 2024-12-03 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_surveyanswer_questionanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='AnswerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='QuestionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Question'),
        ),
    ]
