# Generated by Django 4.2.16 on 2024-12-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_questionanswer_answerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='QuestionText',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='Question',
            new_name='question',
        ),
    ]
