# Generated by Django 4.2.16 on 2024-12-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_answer_answers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='QuestionAnswers',
            new_name='QuestionAnswer',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
