# Generated by Django 4.2.16 on 2024-12-11 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_usersurvey_delete_surveyquestionanswer_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurveyQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersurvey')),
            ],
        ),
    ]
