# Generated by Django 4.2.16 on 2024-12-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_usersurveyquestionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='is_complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
