# Generated by Django 4.2.16 on 2024-12-13 03:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_usersurvey_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='travel_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=app.models.UserSurvey.get_default_month),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='travel_year',
            field=models.IntegerField(default=app.models.UserSurvey.get_default_year),
        ),
    ]
