# Generated by Django 4.2.16 on 2024-12-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_usersurvey_travel_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
