# Generated by Django 4.2.16 on 2024-12-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_itinerary_itinerarydestination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='question_text',
        ),
    ]
