# Generated by Django 4.2.16 on 2024-12-17 06:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_itinerary_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarydestination',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
