# Generated by Django 4.2.16 on 2024-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_itineraryitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraryitem',
            old_name='reservation_needed',
            new_name='booking_required',
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
