# Generated by Django 4.2.16 on 2024-12-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_reservation_needed_itineraryitem_booking_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraryitem',
            old_name='is_free',
            new_name='pre_payment_required',
        ),
    ]
