# Generated by Django 4.2.16 on 2024-12-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_is_free_itineraryitem_pre_payment_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarydestination',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='itinerarydestination',
            name='start_date',
        ),
    ]
