# Generated by Django 4.2.16 on 2024-12-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_itinerarydestination_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='name',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
