# Generated by Django 4.2.16 on 2024-12-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_itinerary_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itinerarydestination',
            constraint=models.UniqueConstraint(fields=('itinerary', 'country', 'city'), name='unique_itinerary_country_city'),
        ),
    ]
