# Generated by Django 4.2.16 on 2025-01-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_itinerarydestination_unique_itinerary_country_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='type',
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=150)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activitytype')),
            ],
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.activitytype'),
            preserve_default=False,
        ),
    ]
