# Generated by Django 4.2.16 on 2025-01-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_itinerary_user_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryitem',
            name='itinerary_destination',
        ),
    ]
