# Generated by Django 4.2.16 on 2025-01-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_itineraryitem_itinerary_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='osm_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='osm_value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
