# Generated by Django 4.2.16 on 2025-01-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_itineraryitem_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='house_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='latitude',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='longitude',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='postal_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
