# Generated by Django 4.2.16 on 2025-01-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_itineraryitem_city_itineraryitem_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryitem',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='activity_type',
        ),
    ]
