# Generated by Django 4.2.16 on 2025-02-02 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_itineraryitem_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=150)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('itinerary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itineraryitem')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transporttype')),
            ],
        ),
    ]
