# Generated by Django 4.2.16 on 2025-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_transporttype_itineraryitem_image_url_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'Transportation'), (2, 'Food & Drinks'), (3, 'Accomodation & Stays'), (4, 'Activities & Tourism'), (5, 'Other')], default=4),
            preserve_default=False,
        ),
    ]
